### PR TITLE
V2

### PR DESCRIPTION
**Pull request by sandfox**
New api - rewritten internals!

### CODE REVIEW

**Comment by defel** [comment]
can you `npm publish` this? :muscle: :)

**Comment by sandfox** [comment]
@defel it's here -> https://www.npmjs.com/package/@sandfox/arn

**Comment by sandfox** [comment]
I should probably add a link/deprecation notice to the v1 package!

**Comment by defel** [comment]
I see, thank you! 
Maybe you can deprecate the old package? ( https://www.npmjs.com/package/aws-arn-parser )


https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions

**Pull request merged**
